"""Public API for the MotionGPT3-derived diffusion-head classifier."""

from .config import (
    DataConfig,
    DiffusionHeadConfig,
    ExperimentConfig,
    GPTConfig,
    TrainingConfig,
    VAEConfig,
    VAETrainingConfig,
    VQVAEConfig,
    VQVAETrainingConfig,
)
from .data import (
    DataBundle,
    FixedGridSplit,
    MotionLatentDataset,
    MotionTokenDataset,
    MotionWindowDataset,
    channel_names,
    load_fold_dataset,
    make_loader,
    modality_channel_slices,
    prepare_data,
    selected_channel_indices,
)
from .model import DiffusionHead, MotionGPT3Classifier, MotionSummarizer, count_parameters
from .training import (
    EvaluationOutput,
    TrainingResult,
    build_embedder,
    evaluate_with_predictions,
    load_training_result_motiongpt3,
    resolve_device,
    set_reproducible_seed,
    tokenize_all_splits,
    tokenizer_statistics,
    train_classifier,
    train_motiongpt3,
    train_tokenizer_stage,
)

__all__ = [
    "DataBundle",
    "DataConfig",
    "DiffusionHead",
    "DiffusionHeadConfig",
    "EvaluationOutput",
    "ExperimentConfig",
    "FixedGridSplit",
    "GPTConfig",
    "MotionGPT3Classifier",
    "MotionLatentDataset",
    "MotionSummarizer",
    "MotionTokenDataset",
    "MotionWindowDataset",
    "TrainingConfig",
    "TrainingResult",
    "VAEConfig",
    "VAETrainingConfig",
    "VQVAEConfig",
    "VQVAETrainingConfig",
    "build_embedder",
    "channel_names",
    "count_parameters",
    "evaluate_with_predictions",
    "load_fold_dataset",
    "load_training_result_motiongpt3",
    "make_loader",
    "modality_channel_slices",
    "prepare_data",
    "resolve_device",
    "selected_channel_indices",
    "set_reproducible_seed",
    "tokenize_all_splits",
    "tokenizer_statistics",
    "train_classifier",
    "train_motiongpt3",
    "train_tokenizer_stage",
]
