"""Public API for T2M-GPT motion-token experiments on VR negation windows."""

from .aggregation import (
    SCORE_METRICS,
    CrossValidationArtifacts,
    aggregate_cross_validation_results,
)
from .config import (
    MODALITY_CHOICES,
    DataConfig,
    ExperimentConfig,
    GPTConfig,
    PretrainingConfig,
    TrainingConfig,
    VQVAEConfig,
    VQVAETrainingConfig,
)
from .data import (
    DataBundle,
    FixedGridSplit,
    MotionTokenDataset,
    MotionWindowDataset,
    channel_names,
    load_fold_dataset,
    make_loader,
    modality_channel_slices,
    prepare_data,
    selected_channel_indices,
)
from .model import MotionTokenGPT, count_parameters, uniform_token_log_likelihood
from .training import (
    EvaluationOutput,
    TrainingResult,
    evaluate_vqvae,
    evaluate_with_predictions,
    load_trained_model,
    load_training_result,
    pretrain_motion_gpt,
    resolve_device,
    set_reproducible_seed,
    token_statistics,
    tokenize_split,
    train_motion_gpt,
    train_motion_vqvae,
    train_t2m_gpt,
)
from .vqvae import (
    MotionVQVAE,
    QuantizeEMAReset,
    QuantizerOutput,
    VQVAEOutput,
    reconstruction_losses,
)

__all__ = [
    "MODALITY_CHOICES",
    "SCORE_METRICS",
    "CrossValidationArtifacts",
    "DataBundle",
    "DataConfig",
    "EvaluationOutput",
    "ExperimentConfig",
    "FixedGridSplit",
    "GPTConfig",
    "MotionTokenDataset",
    "MotionTokenGPT",
    "MotionVQVAE",
    "MotionWindowDataset",
    "PretrainingConfig",
    "QuantizeEMAReset",
    "QuantizerOutput",
    "TrainingConfig",
    "TrainingResult",
    "VQVAEConfig",
    "VQVAEOutput",
    "VQVAETrainingConfig",
    "aggregate_cross_validation_results",
    "channel_names",
    "count_parameters",
    "evaluate_vqvae",
    "evaluate_with_predictions",
    "load_fold_dataset",
    "load_trained_model",
    "load_training_result",
    "make_loader",
    "modality_channel_slices",
    "prepare_data",
    "pretrain_motion_gpt",
    "reconstruction_losses",
    "resolve_device",
    "selected_channel_indices",
    "set_reproducible_seed",
    "token_statistics",
    "tokenize_split",
    "train_motion_gpt",
    "train_motion_vqvae",
    "train_t2m_gpt",
    "uniform_token_log_likelihood",
]
