"""Public API for the continuous-latent VAE variant of T2M-GPT."""

from .config import (
    DataConfig,
    ExperimentConfig,
    GPTConfig,
    PretrainingConfig,
    TrainingConfig,
    VAEConfig,
    VAETrainingConfig,
)
from .data import (
    DataBundle,
    FixedGridSplit,
    MotionLatentDataset,
    MotionWindowDataset,
    channel_names,
    load_fold_dataset,
    make_loader,
    modality_channel_slices,
    prepare_data,
    selected_channel_indices,
)
from .model import MotionLatentGPT, count_parameters
from .training import (
    EvaluationOutput,
    TrainingResult,
    evaluate_vae,
    evaluate_with_predictions,
    latent_statistics,
    load_trained_model_v2,
    load_training_result_v2,
    pretrain_motion_latent_gpt,
    resolve_device,
    set_reproducible_seed,
    tokenize_split_continuous,
    train_motion_latent_gpt,
    train_motion_vae,
    train_t2m_gpt_v2,
)
from .vae import MotionVAE, VAEOutput, kl_divergence_loss, reparameterize

__all__ = [
    "DataBundle",
    "DataConfig",
    "EvaluationOutput",
    "ExperimentConfig",
    "FixedGridSplit",
    "GPTConfig",
    "MotionLatentDataset",
    "MotionLatentGPT",
    "MotionVAE",
    "MotionWindowDataset",
    "PretrainingConfig",
    "TrainingConfig",
    "TrainingResult",
    "VAEConfig",
    "VAEOutput",
    "VAETrainingConfig",
    "channel_names",
    "count_parameters",
    "evaluate_vae",
    "evaluate_with_predictions",
    "kl_divergence_loss",
    "latent_statistics",
    "load_fold_dataset",
    "load_trained_model_v2",
    "load_training_result_v2",
    "make_loader",
    "modality_channel_slices",
    "prepare_data",
    "pretrain_motion_latent_gpt",
    "reparameterize",
    "resolve_device",
    "selected_channel_indices",
    "set_reproducible_seed",
    "tokenize_split_continuous",
    "train_motion_latent_gpt",
    "train_motion_vae",
    "train_t2m_gpt_v2",
]
